import type { Metadata } from "next";
import { Orbitron, Urbanist } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--font-urbanist",
});

const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${orbitron.variable} ${urbanist.variable} antialiased bg-[#020617]`}
      >
        {children}
      </body>
    </html>
  );
}
